<?php
$title = 'Enviar o email';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div class="page-header">
<form action= "<?php echo $this->basepath('usuario/envio/enviar') ?>" method="post" class="form-horizontal" role="form">
    <div class="form-group">
    	<label for="nome" class="col-sm-2 control-label">Para</label>
    	<div class="col-sm-3">
    		<input type='email' name='email' class='form-control' placeholder='Email' /> 
    	</div>
    </div>
    <div class="form-group">
    	<label for="nome" class="col-sm-2 control-label">Assunto</label>
    	<div class="col-sm-3">
    		<input type='text' name='assunto' class='form-control' placeholder='Assunto' /> 
    	</div>
    </div>
    <div class="form-group">
    	<label for="email" class="col-sm-2 control-label">Texto do Email</label>
    	<div class="col-sm-3">
    		<textarea  name='corpoEmail' class='form-control' placeholder='Texto do Email'></textarea> 
    	</div>
    </div>
    <div class="form-group">
    	<div class="col-sm-offset-2 col-sm-4">
    		<input type="submit" value="Enviar Email" class="btn btn-default" />
    	</div>
    </div>
</form>
</div>