<?php
$title = 'Autenticação';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<div class="page-header">
<form action="<?php echo $this->basepath("autenticar/autenticar") ?>" method="post" class="form-horizontal" role="form">
    <div class="form-group">
    	<label for="modelo" class="col-sm-2 control-label">Login</label>
    	<div class="col-sm-3">
    		<input type="text" name="login" id="login" placeholder="Login" class="form-control"  />
    	</div>
    </div>
    <div class="form-group">
    	<label for="modelo" class="col-sm-2 control-label">Senha</label>
    	<div class="col-sm-3">
    		<input type="password" name="senha" id="senha" placeholder="Senha" class="form-control"  />
    	</div>
    </div>
    <div class="form-group">
    	<div class="col-sm-offset-2 col-sm-4">
    		<input type="submit" name="submit" value="Logar" class="btn btn-default" />
    	</div>
    </div>
</form>
</div>